### ISSUE TITLE
Add pep8

### ISSUE THREAD

**Issue by Ana06** [openSUSE/trollolo#154]
Trollolo has some Python code. We should add [pep8](https://www.python.org/dev/peps/pep-0008), Python standard style checker to the project. It would need to be documented in the [Contributing guide](https://github.com/openSUSE/trollolo/blob/master/CONTRIBUTING.md) and run in Travis.

**Comment by Ronaq13** [comment]
I want to work on this.

**Comment by Ana06** [comment]
@Ronaq13 please focus on finishing your other PRs because assigning your self more issues. If you are waiting for your other PR to be reviewed, you can in the meanwhile read about Scrum, or the documentation of the Trello API, etc. (i can point you to resources if you needed it). That you open more PR makes that you end with many things unfinished. And with that many PRs, It will take me longer until I can review everything. :wink:

**Comment by Ronaq13** [comment]
Sorry for these multiple PRs. @Ana06 actually I want to understand the project code, architecture, and present feature so I thought, if I could solve issues then that would help in doing so. That's why I did. I will keep this in mind now.

Yes please give me resources by which I can understand the current architecture of this project. These things would help me in making a good architecture/code-style for the new features we want in this project.

Thank you for your help, it's great working with you.

**Comment by chocoelho** [comment]
@Ana06 in this case, [flake8](https://github.com/PyCQA/flake8) is usually the default linter used on Python code bases. Also, there's [pylint](https://github.com/PyCQA/pylint) as well, which deals with even more issues that may arise. Which would you rather start with?

**Comment by Ana06** [comment]
flake8 is running pep8 and more stuff, right? I am fine with using flake8 too. @Ronaq13 would you like to update your PR to use flake 8 instead of pep8? :smiley:

**Comment by Ronaq13** [comment]
We can use flake8. But I thinnk making a spearate PR for this will be fine. Updating the current one will take more time. Then we can choose which one to have.
